[workspace]
resolver = "3"
members=["library", "examples/json_fibonacci", "examples/json_to_bencode" , "examples/json_to_yaml", "examples/json_to_xml", "examples/json_pretty_print", "examples/json_strip_whitespace", "examples/json_create_at_runtime"]
